// Daftar adegan foto per kategori. BERKAS DATA MURNI, tanpa efek samping.
//
// Dipakai dua tempat sekaligus:
//   - lengkapi-foto.mjs  -> untuk menggenerate gambarnya
//   - assign-images.mjs  -> untuk tahu foto itu milik kategori mana
//
// Disatukan supaya tidak terulang lagi: sudah DUA KALI foto digenerate lalu
// lupa didaftarkan ke POOL, jadi filenya ada di disk tapi tidak pernah dipakai
// artikel mana pun. Sekarang cukup tambah satu baris di sini, keduanya ikut.

export const ADEGAN = {
  'Aksi Korporasi': [
    ['paparan-publik', 'Company executives presenting at a public expose event, seated analysts taking notes in the foreground, hotel function room'],
    ['jabat-tangan-direksi', 'Two Indonesian executives shaking hands after an agreement, colleagues applauding softly behind, warm indoor light'],
    ['lorong-kantor-pusat', 'Employees walking down a bright modern office corridor carrying folders, glass partitions on both sides'],
    ['rapat-komite', 'Small committee meeting around a round table, five people in discussion, notepads and coffee cups'],
    ['lobi-lift-kantor', 'Executives waiting at a marble elevator lobby in a Jakarta office tower, morning light from tall windows'],
    ['arsip-berkas', 'Rows of archive boxes and ring binders on metal shelves in a company records room'],
    ['meja-notaris', 'Notary desk with an embossing seal and stamp pad, hands of two signatories out of focus behind'],
    ['resepsionis-korporat', 'Corporate reception desk with a receptionist greeting a visitor, plants and soft lighting'],
    ['lobi-bursa', 'People walking through the spacious lobby of a stock exchange building, high ceiling and daylight'],
    ['presentasi-jauh', 'Presenter gesturing toward a projection screen, photographed from the back of a full audience, screen out of focus'],
    ['tangga-kaca-kantor', 'Executives descending a glass and steel staircase inside a modern corporate atrium'],
    ['ruang-tunggu-eksekutif', 'Executive waiting lounge with leather armchairs and a low table, city view through the window'],
    ['serah-terima-map', 'Close up of a document folder being handed from one person to another across a desk'],
    ['rapat-daring', 'Over the shoulder view of a laptop showing a grid video call, notebook and pen beside it on a desk'],
    ['papap-strategi', 'People standing at a whiteboard covered in abstract boxes and arrows, discussing, no legible writing'],
    ['tiba-di-kantor', 'Executive stepping out of a car at the entrance of a corporate building, driver holding the door'],
    ['kopi-rapat', 'Coffee cups, notebooks and reading glasses left on a meeting table mid discussion, people blurred behind'],
    ['jendela-kota-malam', 'Executive standing at a floor to ceiling window looking over Jakarta at night, seen from behind'],
    ['berkas-disortir', 'Hands sorting stacks of paper folders on a large desk, several piles arranged'],
    ['foto-bersama-korporat', 'Group of executives standing together for a photo moment after a ceremony, applause, indoor stage'],
  ],
  'Perbankan': [
    ['agen-laku-pandai', 'Village banking agent serving a customer at a small shopfront counter with a card reader'],
    ['nasabah-desa-antre', 'Rural customers waiting outside a small bank service point, motorbikes parked nearby'],
    ['konter-bank-pagi', 'Bank branch counter early in the morning, staff preparing, empty customer chairs'],
    ['petugas-layani-nasabah', 'Bank officer explaining something to a seated customer across a desk, both in profile'],
    ['mesin-antrean', 'Customer taking a paper queue ticket from a dispenser in a bank lobby'],
    ['bank-mikro-desa', 'Microfinance officer meeting village clients on a wooden porch, motorbike parked nearby'],
    ['kotak-deposit', 'Rows of safe deposit boxes in a bank vault room, one drawer partly open'],
    ['atm-malam', 'Person using a cash machine inside a lit vestibule at night, photographed from outside through the glass, reflections on the pane'],
  ],
  'Moneter': [
    ['sidang-komisi-dpr', 'Parliamentary commission hearing room with legislators seated in tiers facing a witness table'],
    ['pelantikan-pejabat', 'Official swearing in ceremony, hands raised, formal hall with flags out of focus'],
    ['podium-kosong-briefing', 'Empty podium with microphones set up before a press briefing, chairs arranged in rows'],
    ['brankas-uang-sentral', 'Secure cash handling room with sealed containers on trolleys, staff in uniform'],
    ['meja-kebijakan', 'Empty formal meeting room set for a policy session, water glasses and microphones on the table'],
    ['konpers-podium', 'Official speaking at a podium during a press conference, photographers crouched in front'],
    ['pencakar-langit-jakarta', 'Cluster of Jakarta office towers photographed from below at golden hour'],
    ['rapat-dewan-gubernur', 'Formal boardroom meeting with officials seated along a long table, microphones in front of each seat'],
    ['wartawan-menunggu', 'Journalists with cameras and recorders waiting in a hallway before a briefing'],
    ['koin-logam', 'Close up of stacked Indonesian metal coins on a wooden surface, shallow focus'],
    ['layar-pasar-jauh', 'Large market data screens seen from far across a dim room, figures illegible, silhouettes of staff'],
    ['antre-penukaran-valas', 'Customers waiting at a currency exchange counter photographed from behind at waist height, teller hands counting banknotes, rate board outside the frame'],
    ['koridor-bank-sentral', 'Empty marble corridor inside a central bank building, tall columns, morning light falling in stripes across the polished floor'],
    ['mesin-hitung-uang', 'Close up of a banknote counting machine in operation, cashier hands feeding a stack, blurred office behind'],
    ['mobil-dinas-tiba', 'Black official sedan arriving under a government building portico, security officer opening the rear door, slight motion blur'],
    ['bandara-delegasi', 'Officials in batik walking through an airport arrival corridor with aides carrying document cases, daylight from tall windows'],
  ],
  'Pasar Modal': [
    ['layar-indeks-jauh', 'Large market index display seen from a distance across a bright office atrium, figures unreadable'],
    ['rapat-manajer-investasi', 'Fund managers in discussion around a table with printed portfolio sheets'],
    ['grafik-dinding-kantor', 'Printed performance charts pinned along an office wall, a person walking past out of focus'],
    ['investor-muda-diskusi', 'Two young Indonesians discussing over a tablet at a co-working table'],
    ['trader-dua-layar', 'Trader working at a desk with two monitors, seen over the shoulder, screens out of focus'],
    ['kelas-investor', 'Small investor education class, participants at tables facing an instructor'],
    ['papan-berjalan-kabur', 'Running ticker board photographed with motion blur so the figures are unreadable, people passing beneath'],
    ['mencatat-grafik', 'Hand drawing a rising line chart on paper with a pen, calculator beside it'],
    ['lonceng-pembukaan', 'Ceremonial opening bell on a podium at a stock exchange, photographed from the side, small crowd applauding behind, brass bell in sharp focus'],
    ['analis-telepon-malam', 'Financial analyst on a phone call late at night in a dim office, desk lamp lighting stacks of printed reports'],
    ['ruang-rapat-kaca-bursa', 'Empty glass walled meeting room inside an exchange building, chairs pushed in, city skyline through the window'],
    ['sekuritas-lobi-pagi', 'Morning arrivals at a securities firm lobby, employees passing a turnstile, warm backlight from the entrance'],
  ],
  'Makroekonomi': [
    ['pedagang-bawang', 'Market trader arranging red onions and garlic in baskets at a wholesale stall'],
    ['timbangan-pasar', 'Hands weighing vegetables on a traditional scale at a market stall'],
    ['bongkar-muat-truk', 'Workers unloading sacks from a truck at a distribution warehouse in the morning'],
    ['terminal-bus', 'Intercity bus terminal with passengers boarding and luggage being loaded'],
    ['pasar-ikan', 'Fish market in the early morning, vendors sorting the catch on ice'],
    ['jembatan-desa', 'New concrete bridge over a river connecting two villages, a motorbike crossing'],
    ['jalan-raya-padat', 'Busy Jakarta arterial road at rush hour photographed from a pedestrian bridge'],
    ['panen-sawah', 'Farmers harvesting rice in a paddy field, mountains in the far background, morning haze'],
    ['gudang-beras', 'Workers stacking sacks of rice in a large warehouse, forklift in the background'],
    ['konstruksi-perumahan', 'Housing construction site with brick walls going up and workers on scaffolding'],
    ['keranjang-belanja-ibu', 'Woman carrying a woven basket of groceries through a crowded wet market aisle, morning light filtering through plastic roofing'],
  ],
  'Energi': [
    ['pipa-distribusi-gas', 'Industrial gas pipeline running through a facility with valves and gauges'],
    ['pekerja-tambang-helm', 'Mine workers in helmets and hi-vis vests walking toward a site at sunrise'],
    ['pltu-cerobong', 'Coal fired power plant with tall chimneys seen across a field at dusk'],
    ['tambang-batubara-truk', 'Heavy haul trucks carrying coal along a mine road, dust rising'],
    ['spbu-antre', 'Line of motorbikes queueing at a fuel station in an Indonesian town'],
    ['jaringan-listrik', 'High voltage transmission towers crossing green fields at dusk'],
    ['rig-lepas-pantai', 'Offshore oil platform on a calm sea photographed from a supply boat'],
    ['depot-bbm-malam', 'Fuel storage depot at night with floodlights and pipework'],
    ['teknisi-turbin', 'Technician in a hard hat inspecting a large industrial turbine indoors'],
    ['panel-surya-ladang', 'Rows of solar panels across an open field under bright sky, a technician walking between them'],
    ['tabung-lpg-tumpuk', 'Stacked cooking gas cylinders at a distribution depot, a worker rolling one across the concrete yard'],
  ],
  'UMKM': [
    ['pengrajin-rotan', 'Craftsman weaving rattan furniture in a small open workshop'],
    ['kedai-kopi-kecil', 'Small independent coffee shop, barista pouring, a few customers seated'],
    ['pedagang-sayur-keliling', 'Vegetable seller with produce loaded on a motorbike cart in a residential lane'],
    ['konveksi-penjahit', 'Small garment workshop with several tailors at sewing machines, fabric rolls stacked'],
    ['pasar-kerajinan', 'Handicraft market stall with woven baskets and wooden goods, vendor arranging items'],
    ['warung-kelontong', 'Small neighbourhood grocery shop, owner behind the counter, goods stacked to the ceiling'],
  ],
  'BUMN': [
    ['kapal-feri', 'Passenger ferry docking at a port ramp, vehicles waiting to board'],
    ['gardu-listrik', 'Electrical substation with transformers and insulators, technician walking past'],
    ['kereta-stasiun', 'Commuter train arriving at an Indonesian station platform, passengers waiting behind the line'],
    ['terminal-bandara', 'Airport terminal interior with travellers walking, large windows and daylight'],
    ['galangan-kapal', 'Shipyard dry dock with a vessel hull under maintenance, workers on scaffolding, welding sparks'],
    ['truk-logistik-gudang', 'Row of logistics trucks backed into a distribution warehouse loading bay at dawn'],
    ['petugas-lapangan-rompi', 'State utility field crew in safety vests inspecting roadside equipment, service van parked behind'],
  ],
  'Teknologi': [
    ['menara-bts', 'Telecommunication tower against a clear sky with a technician climbing the ladder'],
    ['rapat-tim-teknologi', 'Young tech team in a stand up meeting beside a wall of sticky notes'],
    ['kabel-jaringan', 'Neatly bundled network cables in a rack, hands connecting one patch cord'],
    ['lorong-server', 'Narrow aisle between server racks in a data centre, blue indicator lights'],
    ['pengembang-koding', 'Software developer working at a desk with a mechanical keyboard, screen turned away from camera'],
    ['pemasangan-fiber', 'Crew pulling fibre optic cable into a street duct, orange cones around the open pit, utility van behind'],
  ],
  'Industri': [
    ['gudang-bahan-baku', 'Warehouse of raw material sacks stacked high, worker with a pallet jack'],
    ['jalur-perakitan', 'Factory assembly line with workers in uniform and safety gear at their stations'],
    ['mesin-tekstil', 'Textile mill machinery spinning yarn onto bobbins, an operator adjusting a spool, warm indoor light'],
  ],
  'Ketenagakerjaan': [
    ['pelatihan-vokasi', 'Vocational training class with students at workbenches and an instructor guiding'],
    ['wawancara-kerja', 'Job interview across a small table, applicant holding a folder'],
    ['bursa-kerja-antre', 'Job seekers queueing at a recruitment fair booth holding document folders, indoor hall, banners far out of focus'],
  ],
  // Kategori Bisnis sebelumnya tidak punya adegan sendiri sama sekali, jadi
  // artikelnya meminjam foto kategori lain dan ikut memperparah pengulangan.
  'Bisnis': [
    ['kemasan-produk-gudang', 'Workers packing finished consumer goods into cartons in a small warehouse, tape dispenser in hand'],
    ['negosiasi-dagang-meja', 'Two business people in discussion across a cafe table with product samples between them, city street visible outside'],
  ],
};
